### ISSUE TITLE
Allow to register custom type converters

### ISSUE THREAD

**Issue by AlexFalappa** [j-easy/easy-props#11]
It would be useful to allow programmatic registration of additional _Apache BeanUtils_ converters into a `PropertyInjector` to expand the default set of data type coercion from `String`s.

This could be exposed with a new method on `PropertyInjectorBuilder` for example. Something like `registerConverter(<class>, <converter>)`

I noticed for example that bean fields of type `java.util.Date` are not supported out of the box. With _Apache BeanUtils_ it is necessary to add a new converter specifying the date pattern.

```java
DateConverter converter = new DateConverter();
converter.setPattern("dd/mm/yyyy");
ConvertUtils.register(converter, Date.class);
```

**Comment by benas** [comment]
Hi @AlexFalappa ,

I agree, however I would not leak apache bean utils APIs in the public APIs of Easy Props (otherwise removing the dependency to apache bean utils would be a breaking change).

For this reason, I introduced a new interface called [`TypeConverter`](https://github.com/j-easy/easy-props/blob/4e2b32aa78f18f063e92875293dde31e47fe2fed/src/main/java/org/jeasy/props/converters/TypeConverter.java) and added a method in the builder [`org.jeasy.props.PropertiesInjectorBuilder#registerTypeConverter`](https://github.com/j-easy/easy-props/blob/4e2b32aa78f18f063e92875293dde31e47fe2fed/src/main/java/org/jeasy/props/PropertiesInjectorBuilder.java#L105). This allows to register a custom type converter if needed and falls back to apache converters (current behaviour). You can find an example [here](https://github.com/j-easy/easy-props/blob/4e2b32aa78f18f063e92875293dde31e47fe2fed/src/test/java/org/jeasy/props/PropertiesInjectorImplTest.java#L71). Wdyt? I deployed v3.0.0-SNAPSHOT containing this feature, so if you can give it a try and let me know about your thoughts I would be grateful.

PS: In regards to registering custom apache converters, since `ConvertUtils.register` is static, it is possible to use a custom apache converter today without changing Easy Props. Here is a quick [example](https://gist.github.com/benas/5b52d8784b9ee054cf08bbcaabf23591) that passes with v2.0.1. But it is better indeed to add this feature to Easy Props with a type conversion contract that is library agnostic.

**Comment by benas** [comment]
As mentioned previously, I believe this new `TypeConverter` interface is a good start since it makes the type conversion feature agnostic to any library and future proof in case we decide to remove the dependency to Apache commons-beanutils.

Version 3.0.0 is now released and includes this new API. We can always improve things in the next iteration if necessary.

Thank you for reporting this issue!
