### ISSUE TITLE
Ability to force order of execution of annotation processors

### ISSUE THREAD

**Issue by Gulats** [j-easy/easy-props#16]
Currently annotation processors are stored in a map and the keyset is used to iterate through them which can lead to different order of execution if a field is marked with multiple annotations.

Ideally, the convention is to have the following increasing order of precedence (as per what spring also has) and allow the property to be overridden from multiple source: 
property in file -> environment variable -> system property

```
    PropertyInjector() {
        annotationProcessors = new HashMap<>();
        typeConverters = new HashMap<>();
        // TODO the day we decide to remove the dependency to apache commons-beanutils, register built-in converters here

        //register built-in annotation processors
        annotationProcessors.put(SystemProperty.class, new SystemPropertyAnnotationProcessor());
        annotationProcessors.put(Property.class, new PropertyAnnotationProcessor());
        annotationProcessors.put(I18NProperty.class, new I18NPropertyAnnotationProcessor());
        annotationProcessors.put(Properties.class, new PropertiesAnnotationProcessor());
        annotationProcessors.put(DBProperty.class, new DBPropertyAnnotationProcessor());
        annotationProcessors.put(JNDIProperty.class, new JNDIPropertyAnnotationProcessor());
        annotationProcessors.put(MavenProperty.class, new MavenPropertyAnnotationProcessor());
        annotationProcessors.put(ManifestProperty.class, new ManifestPropertyAnnotationProcessor());
        annotationProcessors.put(EnvironmentVariable.class, new EnvironmentVariableAnnotationProcessor());
    }

    void injectProperty(final Field field, final Object object) throws PropertyInjectionException {
        //Introspect the field for each registered annotation, and delegate its processing to the corresponding annotation processor
        for (Class<? extends Annotation> annotationType : annotationProcessors.keySet()) {
```

**Comment by benas** [comment]
> Currently annotation processors are stored in a map and the keyset is used to iterate through them which can lead to different order of execution if a field is marked with multiple annotations.

Are you trying to inject a property from two (or more) different sources on the same field at the same time? Can you give a code example please and explain your expectations? Thank you upfront.

**Comment by benas** [comment]
@Gulats Any update on this?

**Comment by Gulats** [comment]
@benas yes i am trying to inject a property from more than one source. it is usually a practice to pick up the default parameter from a property but allow the user to override using system/env properties.
here is a simple patch that I created: https://github.com/Gulats/easy-props/commit/0d1a7aa381b4f1f532573c4c799a6b7c6fad9c21

which starts honoring the desired annotation order. then the sample code looks like this:
```
@Getter
@ToString
@Slf4j
public final class Props {

    private static final PropertiesInjector injector = PropertiesInjectorBuilder.aNewPropertiesInjector();
    private static final String PROPERTIES_FILE = "application.properties";
    private static final String PROPERTIES_FILE_DEV = "application-dev.properties";
    private static final String MYX_ENV_KEY = "myx.env";
    private static final String MYX_ENV_VAL_DEV = "dev";

    static {
        if (MYX_ENV_VAL_DEV.equalsIgnoreCase(System.getProperty("myx.env"))) {
            SourceUtil.generateRawStreamUsingSeparator(PROPERTIES_FILE_DEV, null, "=")
                    .forEach(strStream -> {
                        var keyValue = strStream.collect(Collectors.toList());
                        if (System.getProperty(keyValue.get(0)) == null)
                            System.setProperty(keyValue.get(0), keyValue.get(1));
                    });
        }
    }

    @Property(source=PROPERTIES_FILE, key="httpConnectionTimeoutMillis")
    @EnvironmentVariable(value="httpConnectionTimeoutMillis")
    @SystemProperty(value="httpConnectionTimeoutMillis")
    private long httpConnectionTimeoutMillis;

    ...
    
    Props () {
        injector.injectProperties(this);
        System.out.println(String.format("configured props: %s", this));
    }

}
```

NOTE: the order does not depend on how the user declares it on the field.
e.g. the below order of annotation can be anything:
```
    @Property(source=PROPERTIES_FILE, key="httpConnectionTimeoutMillis")
    @EnvironmentVariable(value="httpConnectionTimeoutMillis")
    @SystemProperty(value="httpConnectionTimeoutMillis")
    private long httpConnectionTimeoutMillis;
```
but how we have defined in our contract:
```
        annotationProcessors.put(Property.class, new PropertyAnnotationProcessor());
        annotationProcessors.put(EnvironmentVariable.class, new EnvironmentVariableAnnotationProcessor());
        annotationProcessors.put(SystemProperty.class, new SystemPropertyAnnotationProcessor());
```

**Comment by benas** [comment]
ok thanks for the update. However, there are two issues with this approach:

#### 1. The order of property injection is fixed

In your patch, you used a linked hash map which makes the order fixed and pre-defined by the library (Properties file -> Env. variable -> System property). What if I want to inject the value from an environment variable first, and if the key is absent then fallback to the value from a properties file? This is not possible with the suggested approach.

#### 2. Properties will override each other *systematically*

I tried your patch and noticed that according to the order you defined, the "second" annotation will always override the first one **even if the first one is correctly injected**:

```java
class Bean {
   @Property(source = "myProperties.properties", key = "bean.name") // Foo
   @SystemProperty(value = "bean.name") // Bar
    private String property;
}
```

I understand that the order of annotation declaration does not matter and that the order is the one defined in the linked hash map, but in this example, if I have a property `bean.name=Foo` in `myProperties.properties` and a a system property `bean.name=Bar`, the bean `property` will be set to `Bar` systematically. What I mean is that, If I understand correctly your original request, the goal of adding multiple annotations is to have some kind of fallback mechanism, meaning that if `bean.name` is not defined in the properties file, only then we should fallback to the system property. But it is not the case here. This is because we don't break out of the loop [here](https://github.com/Gulats/easy-props/blob/0d1a7aa381b4f1f532573c4c799a6b7c6fad9c21/src/main/java/org/jeasy/props/PropertyInjector.java#L69) once an annotation processor has been applied. So subsequent processors will override the previous ones.


So to sum up, I agree on the idea of composing annotations, but we should find a way to make it possible to:

* Inject a property from a second source only if the first source is not available (missing key, missing file, etc) and not systematically
* Dynamically define the order in which properties should be injected

It is actually possible to do this with the current version using a custom annotation + its processor and leverage existing processors (See example [here](https://github.com/j-easy/easy-props/commit/ebf5c2e521bf41c4cbd05f21ba7556c699038d30)), but I was thinking about adding an `order` attribute to all annotations to make it possible to dynamically define the order, something like:

```java
class Bean {
   @Property(source = "myProperties.properties", key = "bean.name", order = 1)
   @SystemProperty(value = "bean.name", order = 2)
   private String property;
}
```

In this example, I would expected the property to be injected from the properties file first, and if the key `bean.name` is missing, fallback to the specified system property. The idea is that the order is dynamic, meaning I can also choose to start with the system property first, then fallback to the properties file:

```java
class Bean {
   @SystemProperty(value = "bean.name", order = 1)
   @Property(source = "myProperties.properties", key = "bean.name", order = 2)
    private String property;
}
```

What do you think? I tried to implement this approach [here](https://github.com/j-easy/easy-props/commit/d7274986d769bef168f1c594f872551e7dbb4114) which is deployed in 3.1.0-SNAPSHOT to see how things work, so I would be grateful if you give it a try and share your feedback. Thank you upfront.

**Comment by Gulats** [comment]
@benas  thanks for the detailed response. i will try it out by the coming weekend.

**Comment by benas** [comment]
@Gulats Let's iterate on this. I merged the new `order` attribute in all annotations to dynamically define the property injection order as described in my previous comment. We can improve things if necessary in the next version.
